### PR TITLE
add class `ucsc-block-directory` to directory container.

### PR DESCRIPTION
**Pull request by Herm71**
Add `ucsc-block-directory` class to directory container.

### CODE REVIEW

**Review by knice — APPROVED** [review]
This looks correct. The intent is to add a class to the beginning of any instance of the directory block. In a future update, the class will act as a namespaced and top-level style hook for any stylesheet styles included with the plugin that pertain to the block. 

**This PR does not affect design or functionality of the plugin.** It leaves all previous code intact and simply adds an additional class to the parent element of an instance of the block.

**Comment by knice** [comment]
Leaving the actual merge to @kagarwal-ucsc since the final decision is his. :-)

**Comment by Herm71** [comment]
Damnit! Your comment didn't show up and I went ahead and merged.

**Comment by knice** [comment]
@superkumario64 Can you add a comment on this PR when this code is on CampusPress? It doesn't have to be soon. Whenever you release again.

**Comment by superkumario64** [comment]
The code is on CapusPress.

**Pull request merged**
